import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { allocateInterval } from "../src/domain/allocation-engine.js";
const repo=fs.readFileSync(new URL("../src/repositories/event-repository.js",import.meta.url),"utf8");
const routes=fs.readFileSync(new URL("../src/routes/events.js",import.meta.url),"utf8");
const planner=fs.readFileSync(new URL("../src/repositories/planner-repository.js",import.meta.url),"utf8");
const html=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");
const ev=(id,type,start,end,mode="exclusive",division=2)=>({id,event_type:type,title:id,start_time:start,end_time:end,allocation_mode:mode,resource_division_count:division,manually_changed:type==="manual_event"});
test("manual CRUD repository exists",()=>{assert.ok(repo.includes("createManualCalendarEvent"));assert.ok(repo.includes("updateManualCalendarEvent"));assert.ok(repo.includes("deleteManualCalendarEvent"))});
test("manual write routes protected",()=>{assert.ok(routes.includes('post("/manual",requireEditPin'));assert.ok(routes.includes('put("/manual/:id",requireEditPin'));assert.ok(routes.includes('delete("/manual/:id",requireEditPin'))});
test("planner includes manual_event",()=>assert.ok(planner.includes("'manual_event'")));
test("manual whole pitch conflicts with imported game",()=>{const r=allocateInterval([ev("Turnier","manual_event","15:00","17:00"),ev("Spiel","home_match","16:00","18:00")]);assert.equal(r.conflict,true)});
test("manual non-divisible overlap conflicts",()=>{const r=allocateInterval([ev("A","manual_event","08:00","17:00","exclusive",1),ev("B","manual_event","15:00","16:00","exclusive",1)]);assert.equal(r.conflict,true)});
test("manual hall 2/3 plus 1/3 fits",()=>{const r=allocateInterval([ev("A","manual_event","18:00","19:30","two_thirds",3),ev("B","manual_event","18:00","19:30","one_third",3)]);assert.equal(r.conflict,false)});
test("calendar days are clickable",()=>assert.ok(html.includes('data-date="${esc(d.date)}"')));
test("manual dialog exists",()=>assert.ok(html.includes('id="manualDialog"')));
test("turnier and platzbelegung types exist",()=>{assert.ok(html.includes("<option>Turnier</option>"));assert.ok(html.includes("<option>Platzbelegung</option>"))});
test("manual edit delete UI exists",()=>{assert.ok(html.includes("editManualDialog"));assert.ok(html.includes('id="deleteManual"'))});
test("manual entries marked",()=>assert.ok(html.includes("MANUELL")));
test("4.5.4 manual calendar retained",()=>assert.ok(html.includes('id="manualDialog"')));
