import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const schema=fs.readFileSync(new URL("../src/database/schema.js",import.meta.url),"utf8");
const repo=fs.readFileSync(new URL("../src/repositories/event-repository.js",import.meta.url),"utf8");
const planner=fs.readFileSync(new URL("../src/repositories/planner-repository.js",import.meta.url),"utf8");
const alloc=fs.readFileSync(new URL("../src/domain/allocation-engine.js",import.meta.url),"utf8");
const html=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");
test("manual marker column exists",()=>assert.ok(schema.includes("manually_changed boolean")));
test("manual edit sets marker",()=>assert.ok(repo.includes("manually_changed=true")));
test("official sync clears marker",()=>assert.ok(repo.includes("manually_changed=false")));
test("games list exposes marker",()=>assert.ok(repo.includes("e.manually_changed")));
test("planner exposes marker",()=>assert.ok(planner.includes("e.manually_changed")));
test("allocation sends marker to calendar",()=>assert.ok(alloc.includes("manuallyChanged:Boolean")));
test("calendar displays MANUELL",()=>assert.ok(html.includes("manualBadge")));
test("obsolete reload button removed",()=>assert.ok(!html.includes('id="reload"')));
test("PDF print control exists",()=>assert.ok(html.includes('id="printCalendar"')));
test("A4 landscape print CSS exists",()=>assert.ok(html.includes("@page{size:A4 landscape")));
test("half-season presets exist",()=>{assert.ok(html.includes('value="hinrunde"'));assert.ok(html.includes('value="rueckrunde"'))});
test("custom print range exists",()=>assert.ok(html.includes('value="custom"')));
test("multi-month print pages exist",()=>assert.ok(html.includes("page-break-after:always")));
test("version 4.5.1 visible",()=>assert.match(html,/Sprint 4\.5\.1/));
