import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");
const manifest=JSON.parse(fs.readFileSync(new URL("../public/manifest.json",import.meta.url),"utf8"));
const sw=fs.readFileSync(new URL("../public/service-worker.js",import.meta.url),"utf8");
test("version 5.1.0 visible",()=>assert.match(html,/Sprint 5\.1\.0/));
test("manifest linked",()=>assert.ok(html.includes('rel="manifest"')));
test("PWA standalone",()=>assert.equal(manifest.display,"standalone"));
test("PWA icons configured",()=>{assert.ok(manifest.icons.some(x=>x.sizes==="192x192"));assert.ok(manifest.icons.some(x=>x.sizes==="512x512"))});
test("service worker registered",()=>assert.ok(html.includes('serviceWorker.register("/service-worker.js")')));
test("API is never cached by service worker",()=>assert.ok(sw.includes('u.pathname.startsWith("/api/")')));
test("admin tabs hidden in read mode",()=>{for(const v of ["training","resources","teams","games"])assert.ok(html.includes(`class="tab adminOnly hidden" data-view="${v}"`))});
test("admin mode can reveal tabs",()=>assert.ok(html.includes('document.querySelectorAll(".adminOnly").forEach')));
test("admin logout exists",()=>assert.ok(html.includes('if(pin){pin="";setAdminMode(false);return}')));
test("PDF remains available without admin tab",()=>assert.ok(html.includes('id="printCalendar"')));
test("mobile bottom nav",()=>assert.ok(html.includes('position:fixed;z-index:50;left:0;right:0;bottom:0')));
test("mobile week vertical",()=>assert.ok(html.includes('.days{display:block')));
test("mobile month card list",()=>assert.ok(html.includes('.monthgrid{display:block')));
test("mobile forms one column",()=>assert.ok(html.includes('.formgrid{grid-template-columns:1fr!important}')));
test("safe area supported",()=>assert.ok(html.includes('env(safe-area-inset-bottom)')));
test("read mode month tap is inert",()=>assert.ok(html.includes('if(!pin)return;openManualDialog')));
test("install button exists",()=>assert.ok(html.includes('id="installApp"')));
